# Generated by Django 3.0.7 on 2024-06-03 17:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакт')),
                ('emails', models.TextField(blank=True, verbose_name='Почта')),
                ('site', models.URLField(blank=True, default='example.com')),
                ('address', models.CharField(max_length=123, verbose_name='Адрес')),
                ('title', models.CharField(blank=True, max_length=123, null=True, verbose_name='О нас название')),
                ('about_us', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='О нас')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('video', models.URLField(blank=True, default='https://www.youtube.com/watch?v=jfKfPfyJRdk&ab_channel=LofiGirl')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
