# Generated by Django 3.0.7 on 2024-06-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='time',
            field=models.CharField(blank=True, default='Пн – Сб: 8:00 – 18:30', max_length=123),
        ),
    ]
