version: "3.10"

services:
  app:
    build: .
    volumes:
      - .:/core
      - ./cardealer/static:/app/static
      - ./media:/app/media
    ports:
    - "8016:8016"
    command: bash -c "python manage.py migrate && gunicorn cardealer.wsgi:application -w 4 -b 0.0.0.0:8016"