# Generated by Django 3.0.7 on 2024-05-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20240515_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='state',
        ),
    ]
