# Generated by Django 3.0.7 on 2024-06-03 15:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='1'),
        ),
    ]
